package jutopia.Season_Ticket;

import java.sql.Date;
import java.sql.Timestamp;

public class Season_Ticket_VO {
	
	private String SEASON_TICKET_ID_EMAIL, SEASON_TICKET_NAME, SEASON_TICKET_CAR_NUM, 
	SEASON_TICKET_POSITION, SEASON_TICKET_CAR_KINDS, SEASON_TICKET_PARKING_LOT, 
	SEASON_TICKET_REDUCTION, SEASON_TICKET_DAY_SALE, SEASON_TICKET_START_DATE, 
	SEASON_TICKET_END_DATE, SEASON_TICKET_TEL;

	public String getSEASON_TICKET_ID_EMAIL() {
		return SEASON_TICKET_ID_EMAIL;
	}

	public String getSEASON_TICKET_NAME() {
		return SEASON_TICKET_NAME;
	}

	public void setSEASON_TICKET_NAME(String SEASON_TICKET_NAME) {
		SEASON_TICKET_NAME = SEASON_TICKET_NAME;
	}

	public String getSEASON_TICKET_CAR_NUM() {
		return SEASON_TICKET_CAR_NUM;
	}

	public void setSEASON_TICKET_CAR_NUM(String SEASON_TICKET_CAR_NUM) {
		SEASON_TICKET_CAR_NUM = SEASON_TICKET_CAR_NUM;
	}

	public String getSEASON_TICKET_POSITION() {
		return SEASON_TICKET_POSITION;
	}

	public void setSEASON_TICKET_POSITION(String SEASON_TICKET_POSITION) {
		SEASON_TICKET_POSITION = SEASON_TICKET_POSITION;
	}

	public String getSEASON_TICKET_CAR_KINDS() {
		return SEASON_TICKET_CAR_KINDS;
	}

	public void setSEASON_TICKET_CAR_KINDS(String SEASON_TICKET_CAR_KINDS) {
		SEASON_TICKET_CAR_KINDS = SEASON_TICKET_CAR_KINDS;
	}

	public String getSEASON_TICKET_PARKING_LOT() {
		return SEASON_TICKET_PARKING_LOT;
	}

	public void setSEASON_TICKET_PARKING_LOT(String SEASON_TICKET_PARKING_LOT) {
		this.SEASON_TICKET_PARKING_LOT = SEASON_TICKET_PARKING_LOT;
	}

	public String getSEASON_TICKET_REDUCTION() {
		return SEASON_TICKET_REDUCTION;
	}

	public void setSEASON_TICKET_REDUCTION(String SEASON_TICKET_REDUCTION) {
		this.SEASON_TICKET_REDUCTION = SEASON_TICKET_REDUCTION;
	}

	public String getSEASON_TICKET_DAY_SALE() {
		return SEASON_TICKET_DAY_SALE;
	}

	public void setSEASON_TICKET_DAY_SALE(String SEASON_TICKET_DAY_SALE) {
		this.SEASON_TICKET_DAY_SALE = SEASON_TICKET_DAY_SALE;
	}

	public String getSEASON_TICKET_START_DATE() {
		return SEASON_TICKET_START_DATE;
	}

	public void setSEASON_TICKET_START_DATE(String SEASON_TICKET_START_DATE) {
		this.SEASON_TICKET_START_DATE = SEASON_TICKET_START_DATE;
	}

	public String getSEASON_TICKET_END_DATE() {
		return SEASON_TICKET_END_DATE;
	}

	public void setSEASON_TICKET_END_DATE(String SEASON_TICKET_END_DATE) {
		this.SEASON_TICKET_END_DATE = SEASON_TICKET_END_DATE;
	}

	public String getSEASON_TICKET_TEL() {
		return SEASON_TICKET_TEL;
	}

	public void setSEASON_TICKET_TEL(String SEASON_TICKET_TEL) {
		this.SEASON_TICKET_TEL = SEASON_TICKET_TEL;
	}

	public void setSEASON_TICKET_ID_EMAIL(String SEASON_TICKET_ID_EMAIL) {
		this.SEASON_TICKET_ID_EMAIL = SEASON_TICKET_ID_EMAIL;
	}



}
